### ISSUE TITLE
[Bug] No rating is ugly

### ISSUE THREAD

**Issue by janfrode** [jossi87/climbing-web#153] opened 2024-06-04 07:09 UTC
**Describe the bug**

When ticking of routes one has the option of selecting "no rating" or "zero stars". If selecting "no rating" it shows "x No rating" box in the tickoff list. This is just ugly... I would suggest removing the "no rating" option, and maybe also default to zero stars instead of requiring the user to select a rating.

zero stars to me means "no comment", or "I don't want to bother rating this".

**Comment by janfrode** [comment] 2024-06-04 07:18
(and of course, feel free to close as not-a-bug if you don't agree.. I just thought I should mention this a a nuisance I keep having when using brattelinjer :-)

**Comment by janfrode** [comment] 2024-06-04 12:07
Alternative suggestion would be to default to "I don't want to rate", and not display the ugly box in the list. That would then maybe remove the incentive to actually give a rating, but I'm not sure that makes much difference. At least I've learned to always put zero stars as my default -- I'm not doing it to say the route was crap, just to avoid the "I don't want to rate" box, so if there are more people like my, routes might get unreasonable low scores with the current behaviour :-/

**Comment by jossi87** [comment] 2024-06-04 13:04
Default action can off course be discussed, but I will not change it based on one persons feedback. I have not gotten this request from other people. This does not mean that nobody is on your side, I just don't know what people think yet :)
Personally I like that people now have to choose, either rate, or say that they don't want to.
But to remove "No rating" from tick-list makes no sense to me. Two separate choises (zero stars vs no rating) should not have the same result in the UI. We have to distinguish this one way, and for now I don't have a suggestion on how to do this in a better way. Again, if you (or someone else) has a suggestion, please share it! Is there any icon we could use instead? Available icons: https://react.semantic-ui.com/elements/icon/

**Comment by janfrode** [comment] 2024-06-04 13:45
Maybe do a survey of why 5 persons gave firestarter zero stars. Did they
really think it was that bad of a route? :-)



 -jf

**Comment by jossi87** [comment] 2024-06-04 14:06
I checked Firestarter now, and all five was ticked before no rating was implemented.

No rating was implemented May 27, 2021 : https://github.com/jossi87/climbing-web/commit/a4e9044cdc600dcd4ef4ff0d11c4cd7dbaf2857f
All of these five ticks came before that date (four with date, the one without date is even older):
![image](https://github.com/jossi87/climbing-web/assets/17472908/8b4ba6e9-1883-45c4-b08a-de8732dacfd8)

**Comment by janfrode** [comment] 2024-06-04 14:49
Yes, I noticed just after sending. But, another example then:

https://brattelinjer.no/problem/4906

Lots of zero stars it seems — and it’s not horrible, honestly.


  -jf

**Comment by jossi87** [comment] 2024-06-04 15:34
I gave it zero stars, and I stand by that decission 😅 This is highly subjective off course, but to me, zero stars is not ugly. It's just not above the rest. The neighbour route however (Ablakov), that one deserved a star if you ask me. None of the routes on Nova are 2- or 3-star-great if you ask me (again, highly subjective). But I still liked the crag, it offers shade on hot summer days. What's not to like!

I know that there will be people that share your opinion, and that's totally fine. In the end, I'm for a change here, but to merge no rating and zero stars is not a good solution. Initially we had 1 star as default on buldreinfo (back in 2003), then we changed to zero (2016), and then to todays solution in 2021. The two previous behaviours (1 and 0 stars) gave the wrong average, since a lot of people don't care about giving stars. The data has improved after 2021, even if someone still prefer 0 stars above no rating (as you mentioned).
And I'm happy to change it even further, but I need suggestions on how to improve this.

**Comment by janfrode** [comment] 2024-06-04 17:23
Added Ablakov to my todo list, thanks !

My main gripe is with the visual [❌No rating] vs.  nothing for zero stars,
which doesn’t really indicate one has given zero stars.  Zero stars looks
prettier in the listing. Displaying an empty star for zero stars would
maybe work, or always have 3 stars when rating is given, and fill in the
number of stars to show rating given. I.e, display something like

[No rating]
xxx
Xxx
XXx
XXX

That might give a stronger incentive to not misuse zero stars like I have
been doing..


  -jf

**Comment by jossi87** [comment] 2024-06-04 17:43
Thanks, I will test out a couple of different possibilities as soon as I get time. Will update this issue as soon as I do :)

**Comment by jossi87** [comment] 2024-06-05 08:51
I tried a couple of options. Not easy to find a perfect solution. To always show three icons can feel a bit verbose on small screens. But the best option I found (for now) is to show three stars on individual ticks, but exclude star-outlines on overview pages (e.g. when you look at all problems/routes on a sector). Ticks without rating are now blank.
Can you take a look and let me know what you think? I also removed the popover (it feels redundant).

**Comment by janfrode** [comment] 2024-06-05 20:22
This looks great.

Maybe only using a single star outline for zero stars, and X, XX, XXX would
be less clutter?

x
X
XX
XXX

But I’m perfectly happy with what you have now.

**Comment by jossi87** [comment] 2024-06-06 06:39
I tried that, but the problem is that star-outline looks like one star. It's confusing on routes where all ticks are zero star (it looks like everyone gave it one star).
I'll keep this open for a while, in case I (or other) come up with suggestions to make it better. But I agree with you, it looks better now.

**Comment by jossi87** [comment] 2024-06-09 07:09
Star outline now has opacity 0.5. Looks good, closing the issue :)

**Closed by jossi87** 2024-06-09 07:09 UTC
Labels: bug
